version: 2.1

jobs:
  build-android-lib:
    working_directory: ~/build-android-lib
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: dependencies download command
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: build project
          command: ./gradlew clean assemble
      - run:
          name: run tests
          command: ./gradlew test
  test-android-lib:
    working_directory: ~/build-android-lib
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: ./gradlew test

workflows:
  build_and_test:
    jobs:
      - build-android-lib
      - test-android-lib:
          requires:
            - build-android-lib